import { useEffect, useState } from 'react';
import { workspaceStore } from '../data/workspace';
import { createBundledCatalogSnapshot, importCatalogSnapshot, type CatalogSnapshot } from '../domain/catalog-snapshot';
import { previewCatalogMigration, previewCatalogRollback, cancelCatalogMigration, acceptCatalogMigration, type MigrationPreview } from '../data/catalog-migration';
import { useCatalogRuntime, planRuntimeWorkspace, bindingLabel } from './catalog-runtime';
import type { SnapshotPlan } from '../domain/snapshot-planner';
import type { Workspace } from '../data/workspace';
interface Delta {id:string;before:SnapshotPlan;after:SnapshotPlan}
export function CatalogMigrationPanel() {
 const {runtime,error:loadError}=useCatalogRuntime();
 const [name,setName]=useState(''),[candidate,setCandidate]=useState<CatalogSnapshot>(),[preview,setPreview]=useState<MigrationPreview>(),[deltas,setDeltas]=useState<Delta[]>([]),[ack,setAck]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<{id:string;revision:number}[]>([]);
 const [decisions,setDecisions]=useState<Record<string,'keep'|'migrate'>>({});
 useEffect(()=>{void workspaceStore.ready().then(()=>workspaceStore.migrationHistory.toArray()).then(setHistory).catch(e=>setError(String(e)));},[]);
 useEffect(()=>()=>{if(preview)cancelCatalogMigration(preview.id);},[preview]);
 async function show(p:MigrationPreview,c:CatalogSnapshot){
  if(!runtime)return;
  const data=await workspaceStore.load();
  const nextRuntime={...runtime,resolve:(id:Parameters<typeof runtime.resolve>[0])=>id===c.id?c:runtime.resolve(id)};
  const nextGoals=data.goals.map(g=>{const change=p.changes.find(v=>v.kind==='goal'&&v.id===g.id);return change?{...g,catalogBinding:change.after,recipeId:change.afterRecipeId}:g;});
  const before=planRuntimeWorkspace(runtime,data),after=planRuntimeWorkspace(nextRuntime,{...data,goals:nextGoals});
  const perGoal=(plan:SnapshotPlan,id:string):SnapshotPlan=>{
   const diagnostics=plan.diagnostics.filter(d=>d.goalId===id);
   const rows=(key:'direct'|'raw'|'allocations')=>plan[key].flatMap(r=>r.contributions.filter(c=>c.goalId===id).map(c=>({...r,...c,contributions:[c]})));
   return {...plan,complete:diagnostics.length===0,diagnostics,goals:plan.goals.filter(g=>g.id===id),goalResults:plan.goalResults.filter(g=>g.id===id),steps:plan.steps.filter(s=>s.goalId===id),direct:rows('direct'),raw:rows('raw'),allocations:rows('allocations')};
  };
  setDeltas(data.goals.map(g=>{const prior=perGoal(before,g.id);if(g.catalogBinding?.state!=='bound'||!runtime.resolve(g.catalogBinding.snapshotId))prior.complete=false;return {id:g.id,before:prior,after:perGoal(after,g.id)};}));
  setPreview(p);setError('');
 }
 async function prepare(){try{const c=candidate??await createBundledCatalogSnapshot();setCandidate(c);const data=await workspaceStore.load();const goals=Object.fromEntries(data.goals.map(g=>[g.id,decisions[g.id]??(g.catalogBinding?.state!=='bound'?(ack?'migrate':'keep'):'migrate')]));await show(await previewCatalogMigration(workspaceStore,c,{goals,acknowledgeLegacy:ack}),c);}catch(e){setError(String(e));}}
 if(!runtime)return <p>{loadError||'Loading workspace metadata…'}</p>;
 const rows=(d:Delta,projection:'direct'|'raw')=>{
  if(!d.before.complete)return <p>{projection}: historical calculation unavailable (not zero). Candidate: {d.after.complete?d.after[projection].map(r=>`${r.item} need ${r.required}, missing ${r.missing}`).join('; '):'unresolved'}</p>;
  if(!d.after.complete)return <p>{projection}: candidate unresolved; numeric delta unavailable.</p>;
  const ids=[...new Set([...d.before[projection],...d.after[projection]].map(r=>r.item))];
  return <ul>{ids.map(id=>{const a=d.before[projection].find(r=>r.item===id),b=d.after[projection].find(r=>r.item===id);return <li key={id}>{projection} {id}: need {a?.required??0} → {b?.required??0} (Δ {(b?.required??0)-(a?.required??0)}); missing {a?.missing??0} → {b?.missing??0} (Δ {(b?.missing??0)-(a?.missing??0)})</li>;})}</ul>;
 };
 return <section aria-label="Catalog migration" className="card stack"><h3>Workspace and catalog references</h3><p>Workspace: {runtime.metadata.name} · ID: {runtime.metadata.id} · revision {runtime.metadata.revision}</p><label>Workspace name<input value={name} placeholder={runtime.metadata.name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><button onClick={()=>void workspaceStore.rename(name).then(()=>setError('')).catch(e=>setError(String(e)))}>Save workspace name</button><p>Selected reference for new plans: {runtime.metadata.selectedCatalog}</p><p>Changing reference is explicit. Legacy adoption applies available rules; it does not recover historical rules. Preview and cancel do not write personal data.</p><button onClick={()=>{setCandidate(undefined);setPreview(undefined);setError('');}}>Use bundled candidate</button><label>Import local catalog snapshot<input type="file" accept=".json,application/json" onChange={async e=>{setPreview(undefined);setCandidate(undefined);const f=e.target.files?.[0];if(!f)return;try{if(f.size>10*1024*1024)throw new Error('Snapshot exceeds 10 MiB');setCandidate(await importCatalogSnapshot(JSON.parse(await f.text())));setError('');}catch(e){setError(String(e));}}}/></label><p>Candidate: {candidate?.manifest.datasetId??'Bundled reference'} · {candidate?.id??'computed at preview'}; digest validation is not source trust verification.</p><label><input type="checkbox" checked={ack} onChange={e=>{setAck(e.target.checked);setPreview(undefined);}}/>I acknowledge applying current rules to legacy plans, not recovering history</label><button disabled={!!error} onClick={()=>void prepare()}>Preview catalog migration</button>
 {preview&&<section aria-label="Catalog migration preview"><h4>{preview.rollbackOf?'Rollback':'Migration'} preview</h4><p>Selected {runtime.metadata.selectedCatalog} → {preview.candidateId}. Revision {preview.expectedRevision}. Quantities, progress, notes and inventory timestamps remain unchanged.</p>{preview.references.map(r=><div key={`${r.kind}:${r.id}`}><p>{r.kind} {r.id}: {bindingLabel({catalogBinding:r.before} as Workspace['goals'][number])} → {bindingLabel({catalogBinding:r.after} as Workspace['goals'][number])}; {r.status}; unknown/changed IDs: {r.references.join(', ')||'none'}; decision {r.decision}</p>{r.kind==='goal'&&<label>Decision for {r.id}<select value={decisions[r.id]??r.decision} onChange={e=>{setDecisions({...decisions,[r.id]:e.target.value as 'keep'|'migrate'});setPreview(undefined);}}><option value="keep">Keep old binding</option><option value="migrate">Migrate</option></select></label>}</div>)}{preview.changes.map(c=><p key={`${c.kind}:${c.id}`}>{c.kind} {c.id}: {c.before.state==='bound'?c.before.snapshotId:c.before.state} → {c.after.state==='bound'?c.after.snapshotId:c.after.state} · recipe {c.beforeRecipeId??'unknown'} → {c.afterRecipeId??'unknown'}</p>)}{deltas.map(d=><section key={d.id}><h5>Goal {d.id} · queue-priority allocation using current stock</h5><p>Batch/output/surplus: {d.before.complete?JSON.stringify(d.before.goals.map(g=>[g.batches,g.output,g.surplus])):'historical calculation unavailable'} → {d.after.complete?JSON.stringify(d.after.goals.map(g=>[g.batches,g.output,g.surplus])):'unresolved'}</p>{rows(d,'direct')}{rows(d,'raw')}{d.after.diagnostics.map((v,i)=><p key={i}>{v.code}: {v.path.join(' → ')}</p>)}</section>)}<button onClick={()=>{cancelCatalogMigration(preview.id);setPreview(undefined);}}>Cancel catalog migration</button><button onClick={async()=>{try{await acceptCatalogMigration(workspaceStore,preview.id,preview.expectedRevision);await workspaceStore.personalMetadata();window.location.reload();}catch(e){setError(String(e));}}}>Accept catalog migration</button></section>}
 <h4>Migration history</h4>{history.sort((a,b)=>b.revision-a.revision).map(h=><button key={h.id} onClick={async()=>{try{const p=await previewCatalogRollback(workspaceStore,h.id);const c=await workspaceStore.resolveSnapshot(p.candidateId as CatalogSnapshot['id']);if(!c)throw new Error('Prior snapshot missing');await show(p,c);}catch(e){setError(String(e));}}}>Preview rollback revision {h.revision}</button>)}{error&&<p role="alert">{error}. No successful change claimed; preview again after concurrent edits.</p>}</section>;
}
