import { useState } from 'react';
import { catalog, itemName, materials } from '../domain/catalog';
import type { Goal } from '../domain/planner';
import type { WorkspaceProps } from './Craft';
function GoalEditor({goal,onSave}:{goal:Goal;onSave:(g:Goal)=>void}) { const [error,setError]=useState(''); return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const quantity=Number(f.get('quantity')),completed=Number(f.get('completed'));if(!Number.isSafeInteger(quantity)||quantity<1||!Number.isSafeInteger(completed)||completed<0||completed>quantity){setError('Use whole numbers; progress must be between zero and quantity.');return;}setError('');onSave({...goal,quantity,completed,notes:String(f.get('notes'))});}}><label>Goal quantity<input name="quantity" type="number" min="1" defaultValue={goal.quantity}/></label><label>Completed units<input name="completed" type="number" min="0" defaultValue={goal.completed}/></label><label>Notes<textarea name="notes" defaultValue={goal.notes}/></label>{error&&<p role="alert">{error}</p>}<button>Save goal</button></form>; }
export function Queue({data,update}:WorkspaceProps) {
 const change=(goal:Goal)=>void update({...data,goals:data.goals.map(g=>g.id===goal.id?goal:g)});
 const move=(index:number,delta:number)=>{const goals=[...data.goals];[goals[index],goals[index+delta]]=[goals[index+delta],goals[index]];void update({...data,goals});};
 return <section className="card"><h2>Pinned craft queue</h2><p>Craft-more goals: existing target stock does not cancel your goal. Completion is progress-only; inventory stays manual.</p>{!data.goals.length&&<p>No plans yet. Search and pin a recipe to begin.</p>}<ol className="goal-list">{data.goals.map((g,i)=><li key={g.id}><h3>{itemName(g.item)} · {g.completed} / {g.quantity}</h3>{!catalog.recipes.some(r=>r.id===g.item)&&<p>Blocked: unknown recipe retained.</p>}{g.notes&&<p>{g.notes}</p>}<div className="actions"><button disabled={i===0} aria-label={`Move ${itemName(g.item)} up`} onClick={()=>move(i,-1)}>↑ Priority</button><button disabled={i===data.goals.length-1} aria-label={`Move ${itemName(g.item)} down`} onClick={()=>move(i,1)}>↓ Priority</button><button disabled={g.completed===g.quantity||!catalog.recipes.some(r=>r.id===g.item)} aria-label={`Complete ${itemName(g.item)}`} onClick={()=>change({...g,completed:g.quantity})}>Complete (progress only)</button><button onClick={()=>void update({...data,goals:data.goals.filter(v=>v.id!==g.id)})}>Remove {itemName(g.item)}</button></div><details><summary>Edit {itemName(g.item)} / partial progress</summary><GoalEditor key={`${g.quantity}:${g.completed}:${g.notes}`} goal={g} onSave={change}/></details></li>)}</ol></section>;
}
export function Inventory({data,update}:WorkspaceProps) { const [error,setError]=useState(''); const ids=[...new Set([...materials.map(m=>m.id),...Object.keys(data.stock)])];return <section className="card"><h2>Manual inventory</h2><p>Enter physical stock only, not planned output. Saved locally; completion never changes these counts.</p>{error&&<p role="alert">{error}</p>}<div className="inventory-grid">{ids.map(id=><form key={`${id}:${data.stock[id]??0}`} onSubmit={e=>{e.preventDefault();const n=Number(new FormData(e.currentTarget).get('stock'));if(!Number.isSafeInteger(n)||n<0){setError('Stock must be a nonnegative safe whole number.');return;}setError('');void update({...data,stock:{...data.stock,[id]:n}});}}><label>{itemName(id)} stock<input aria-label={`${itemName(id)} stock`} name="stock" type="number" min="0" step="1" defaultValue={data.stock[id]??0}/></label><button aria-label={`Save ${itemName(id)} stock`}>Save</button></form>)}</div></section>; }
