import { catalog, itemName, materials } from '../domain/catalog';
import { plan, type Row, type Goal } from '../domain/planner';
import type { Workspace } from '../data/workspace';
import styles from './crafting.module.css';
export function ResourceRows({rows,goals=[]}:{rows:Row[];goals?:Goal[]}) { return <ul className="resource-list">{rows.map(r=><li key={r.item}><strong>{itemName(r.item)}</strong><span>Need {r.required} · Have {r.have} · Reserved {r.reserved} · Planned {r.planned} · Missing {r.missing}</span><details className={styles.provenance}><summary>Contributing goals for {itemName(r.item)}</summary><p>Attributed in queue order from this list's single allocation ledger. Need is demand; Missing is after owned reservations and planned reuse. Reordering can change attribution.</p><ul>{r.contributions.map(c=>{const index=goals.findIndex(g=>g.id===c.goalId);const goal=goals[index];return <li key={c.goalId}>Goal {index+1} · {goal?itemName(goal.item):c.goalId}{goal?.notes?` · ${goal.notes}`:''}: Need {c.required} · Reserved {c.reserved} · Planned {c.planned} · Missing {c.missing}</li>;})}</ul></details></li>)}</ul>; }
export function Shopping({data}:{data:Workspace}) {
 let p:ReturnType<typeof plan>; try{p=plan(catalog,data.goals,data.stock);}catch{return <section className="card" role="alert">Plan blocked: quantities exceed safe calculation limits. Edit or remove the affected goal; your data is retained.</section>;}
 return <section className="card"><h2>Combined shopping list</h2><p>Queue priority allocates each owned item once. Reservations are estimates, not inventory changes.</p>{p.blocked.length>0&&<p role="alert">Blocked unknown recipes: {p.blocked.join(', ')}. Retained for backup; no ready claim.</p>}<h3>Direct ingredients (default)</h3><ResourceRows goals={data.goals} rows={p.direct}/>{!p.direct.length&&<p>No active known ingredient requirements.</p>}<details><summary>Raw-material alternative & dependency steps</summary><p>Alternative to the direct list — do not add the two together. Owned intermediates are used before expanding shortages; planned batch surplus is reused. Stations are not included.</p><ResourceRows goals={data.goals} rows={p.raw}/><h4>Intermediate allocation</h4><ResourceRows goals={data.goals} rows={p.allocations.filter(r=>catalog.recipes.some(c=>c.id===r.item))}/><h4>Craft order (ingredients before consumers)</h4><ol>{p.steps.map((s,i)=><li key={i}>{itemName(s.item)}: {s.batches} batches → {s.output}</li>)}</ol>{p.raw.filter(r=>r.missing>0).map(r=>{const m=materials.find(m=>m.id===r.item)!;return <p key={r.item}>{m.name}: {m.acquisition?.join('; ')} · <a href={m.source.revision_url??m.source.url} target="_blank" rel="noreferrer">Acquisition source</a></p>;})}</details></section>;
}
