import type { Row, Goal } from '../domain/planner';
import type { Workspace } from '../data/workspace';
import { useCatalogRuntime, planRuntimeWorkspace, goalSnapshot, goalItemName, snapshotItemName } from './catalog-runtime';
import styles from './crafting.module.css';
export function ResourceRows({rows,goals=[],name=(id:string)=>id,goalName=(g:Goal)=>g.item}:{rows:Row[];goals?:Goal[];name?:(id:string)=>string;goalName?:(g:Goal)=>string}) {return <ul className="resource-list">{rows.map(r=><li key={r.item}><strong>{name(r.item)}</strong><span>Need {r.required} · Have {r.have} · Reserved {r.reserved} · Planned {r.planned} · Missing {r.missing}</span><details className={styles.provenance}><summary>Contributing goals for {name(r.item)}</summary><p>Attributed in queue order from this list's single allocation ledger. Direct and raw projections are alternatives, never additive.</p><ul>{r.contributions.map(c=>{const index=goals.findIndex(g=>g.id===c.goalId),g=goals[index];return <li key={c.goalId}>Goal {index+1} · {g?goalName(g):c.goalId}{g?.notes?` · ${g.notes}`:''}: Need {c.required} · Reserved {c.reserved} · Planned {c.planned} · Missing {c.missing}</li>;})}</ul></details></li>)}</ul>;}
export function Shopping({data}:{data:Workspace}) {
 const {runtime,error}=useCatalogRuntime();
 if(!runtime)return <p role="status">{error||'Loading bound catalog references…'}</p>;
 const p=planRuntimeWorkspace(runtime,data);
 const name=(id:string)=>{const g=data.goals.find(g=>p.goalResults.some(r=>r.id===g.id&&r.status==='resolved')&&goalSnapshot(runtime,g)?.craft.items.some(i=>i.id===id));return snapshotItemName(g?goalSnapshot(runtime,g):undefined,id);};
 const props={goals:data.goals,name,goalName:(g:Goal)=>goalItemName(runtime,g)};
 return <section className="card"><h2>Combined shopping list</h2><p>Queue priority allocates each owned item once. Reservations are estimates, not inventory changes. Resolved goals only.</p>{!p.complete&&<div role="alert"><p>Some goals unresolved — no whole-queue ready claim. Adopt legacy references explicitly in Settings.</p><ul>{p.diagnostics.map((d,i)=><li key={i}>{d.goalId}: {d.code} · {d.path.join(' → ')}</li>)}</ul></div>}<h3>Direct ingredients (default)</h3><ResourceRows {...props} rows={p.direct}/>{!p.direct.length&&<p>{p.complete?'No active ingredient requirements.':'No resolved ingredient requirements; unresolved goals remain.'}</p>}<details><summary>Raw-material alternative & dependency steps</summary><p>Alternative to the direct list — do not add the two together. Owned intermediates are used before expanding shortages; planned batch surplus is reused. Stations are not included.</p><ResourceRows {...props} rows={p.raw}/><h4>Intermediate allocation</h4><ResourceRows {...props} rows={p.allocations.filter(r=>!p.raw.some(raw=>raw.item===r.item))}/><h4>Craft order (ingredients before consumers)</h4><ol>{p.steps.map((s,i)=><li key={i}>{snapshotItemName(runtime.resolve(s.snapshotId),s.item)}: {s.batches} batches → {s.output} · recipe {s.recipeId} · {s.snapshotId}</li>)}</ol>{p.raw.filter(r=>r.missing>0).flatMap(r=>r.contributions.map(c=>{const g=data.goals.find(g=>g.id===c.goalId);const m=g?goalSnapshot(runtime,g)?.craft.items.find(i=>i.id===r.item):undefined;return m?<p key={`${r.item}:${c.goalId}`}>{m.name}: {m.acquisition?.join('; ')||'Acquisition information unavailable'} · <a href={m.source.revision_url??m.source.url}>Acquisition source</a> · Goal {c.goalId}</p>:null;}))}</details></section>;
}
