import {test,expect} from '@playwright/test';
const url='http://127.0.0.1:4287';
test('snapshot pin, legacy cancel/adopt and rollback retain later quantities',async({page})=>{
 await page.goto(url+'/#/craft');
 await page.getByRole('button',{name:'Select Pal Sphere',exact:true}).click();
 await page.getByRole('button',{name:'Pin craft goal',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Pal Sphere · 0 / 1',exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('heading',{name:'Pal Sphere · 0 / 1',exact:true})).toBeVisible();
 const bound=await page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));return (await workspaceStore.load()).goals[0];});
 expect(bound.catalogBinding.state).toBe('bound');expect(bound.recipeId).toBe('pal-sphere');
 await page.goto(url+'/#/settings');
 await page.getByLabel('Backup JSON',{exact:true}).fill(JSON.stringify({version:1,goals:[{id:'legacy',item:'pal-sphere',quantity:2,completed:0,notes:'retained'}],stock:{wood:3},recent:[]}));
 await page.getByRole('button',{name:'Preview import',exact:true}).click();await page.getByRole('button',{name:'Confirm replace',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Workspace and catalog references'})).toBeVisible();
 const revision=()=>page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));return (await workspaceStore.personalMetadata()).revision;});
 const before=await revision();
 await page.getByRole('button',{name:'Preview catalog migration',exact:true}).click();
 await expect(page.getByRole('region',{name:'Catalog migration preview'})).toContainText('historical');
 await page.getByRole('button',{name:'Cancel catalog migration',exact:true}).click();expect(await revision()).toBe(before);
 await page.getByRole('checkbox',{name:/I acknowledge/}).check();await page.getByRole('button',{name:'Preview catalog migration',exact:true}).click();await page.getByRole('button',{name:'Accept catalog migration',exact:true}).click();
 await expect(page.getByRole('button',{name:/Preview rollback revision/}).first()).toBeVisible();
 await page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));const data=await workspaceStore.load();data.goals[0].quantity=7;await workspaceStore.save(data);});
 await page.getByRole('button',{name:/Preview rollback revision/}).first().click();await page.getByRole('button',{name:'Accept catalog migration',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Workspace and catalog references'})).toBeVisible();
 const reverted=await page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));return (await workspaceStore.load()).goals[0];});
 expect(reverted.quantity).toBe(7);expect(reverted.catalogBinding.state).toBe('legacy-unbound');
});
test('validated synthetic alternate persists and partial unknown never consumes stock twice',async({page})=>{
 await page.goto(url+'/#/craft');await page.getByRole('button',{name:'Select Pal Sphere',exact:true}).waitFor();
 const payload=await page.evaluate(async()=>{
  const {createBundledCatalogSnapshot,createCatalogSnapshot}=await import(/* @vite-ignore */ String('/src/domain/catalog-snapshot.ts'));
  const bundled=await createBundledCatalogSnapshot();const {id,...candidate}=JSON.parse(JSON.stringify(bundled));void id;
  candidate.manifest.datasetId='SYNTHETIC BROWSER FIXTURE — not game facts';
  const ingot=candidate.craft.recipes.find((r:{id:string})=>r.id==='ingot');candidate.craft.recipes.push({...ingot,id:'fixture-ingot-alt',variant:'Synthetic cheaper ingot fixture',inputs:[{item:'ore',count:1}]});
  const sphere=candidate.craft.recipes.find((r:{id:string})=>r.id==='pal-sphere');candidate.craft.recipes.push({...sphere,id:'fixture-sphere-alt',variant:'Synthetic root fixture',inputs:[{item:'ingot',count:2},{item:'wood',count:3}]});
  return JSON.stringify(await createCatalogSnapshot(candidate));
 });
 await page.goto(url+'/#/settings');await page.getByLabel('Import local catalog snapshot').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(payload)});
 await expect(page.getByRole('region',{name:'Catalog migration',exact:true})).toContainText('SYNTHETIC BROWSER FIXTURE');
 await page.getByRole('button',{name:'Preview catalog migration',exact:true}).click();await page.getByRole('button',{name:'Accept catalog migration',exact:true}).click();
 await expect(page.getByRole('button',{name:/Preview rollback revision/}).first()).toBeVisible();
 await page.goto(url+'/#/craft');await page.getByRole('button',{name:'Select Pal Sphere',exact:true}).click();await page.getByLabel('Root recipe',{exact:true}).selectOption('fixture-sphere-alt');
 await page.getByText('Recipe ingredient tree',{exact:true}).click();await page.locator('summary').filter({hasText:/Pal Sphere: 1 units/}).click();await page.locator('summary').filter({hasText:/Ingot: 2 units/}).click();await page.getByLabel('Recipe for Ingot',{exact:true}).selectOption('fixture-ingot-alt');
 await page.getByRole('button',{name:'Pin craft goal',exact:true}).click();await expect(page.getByRole('heading',{name:'Pal Sphere · 0 / 1',exact:true})).toBeVisible();await page.reload();
 const saved=await page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));const data=await workspaceStore.load();const g=data.goals[0];await workspaceStore.save({...data,goals:[g,{...g,id:'second'},{...g,id:'unknown',item:'absent'}],stock:{wood:4,ore:1}});return g;});
 expect(saved.recipeId).toBe('fixture-sphere-alt');expect(saved.recipeOverrides.ingot).toBe('fixture-ingot-alt');await page.reload();
 await expect(page.getByText(/Some goals unresolved/)).toBeVisible();
 const planning=await page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));const {loadCatalogRuntime,planRuntimeWorkspace}=await import(/* @vite-ignore */ String('/src/features/catalog-runtime.ts'));return planRuntimeWorkspace(await loadCatalogRuntime(),await workspaceStore.load());});
 expect(planning.complete).toBe(false);expect(planning.goals).toHaveLength(2);expect(planning.direct.find((r:{item:string})=>r.item==='wood').reserved).toBe(4);expect(planning.raw.find((r:{item:string})=>r.item==='ore').reserved).toBe(1);
});

test('synthetic candidate numeric deltas share queue stock; cancel is inert and missing bytes never fall back',async({page})=>{
 await page.goto(url+'/#/craft');
 await page.getByRole('button',{name:'Select Arrow',exact:true}).click();
 await page.getByLabel('Desired finished units').fill('11');
 await page.getByRole('button',{name:'Pin craft goal',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Arrow · 0 / 11',exact:true})).toBeVisible();
 const fixture=await page.evaluate(async()=>{
  const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));
  const {createCatalogSnapshot}=await import(/* @vite-ignore */ String('/src/domain/catalog-snapshot.ts'));
  const data=await workspaceStore.load();const first={...data.goals[0],id:'first'},second={...first,id:'second'};
  await workspaceStore.save({...data,goals:[first,second],stock:{wood:3}});
  const original=await workspaceStore.resolveSnapshot(first.catalogBinding.snapshotId);
  const {id,...candidate}=JSON.parse(JSON.stringify(original));void id;
  candidate.manifest.datasetId='SYNTHETIC NUMERIC DELTA FIXTURE — not game facts';
  candidate.craft.recipes.find((r:{id:string})=>r.id==='arrow').inputs.find((i:{item:string})=>i.item==='wood').count=3;
  return {payload:JSON.stringify(await createCatalogSnapshot(candidate)),backup:await workspaceStore.export(),revision:(await workspaceStore.personalMetadata()).revision};
 });
 await page.goto(url+'/#/settings');
 await page.getByLabel('Import local catalog snapshot').setInputFiles({name:'synthetic-delta.json',mimeType:'application/json',buffer:Buffer.from(fixture.payload)});
 await expect(page.getByRole('region',{name:'Catalog migration',exact:true})).toContainText('SYNTHETIC NUMERIC DELTA FIXTURE');
 await page.getByRole('button',{name:'Preview catalog migration',exact:true}).click();
 const first=page.getByRole('heading',{name:'Goal first · queue-priority allocation using current stock'}).locator('..');
 const second=page.getByRole('heading',{name:'Goal second · queue-priority allocation using current stock'}).locator('..');
 await expect(first).toContainText('direct wood: need 4 → 6 (Δ 2); missing 1 → 3 (Δ 2)');
 await expect(second).toContainText('direct wood: need 2 → 3 (Δ 1); missing 2 → 3 (Δ 1)');
 await page.getByRole('button',{name:'Cancel catalog migration',exact:true}).click();
 const unchanged=await page.evaluate(async()=>{const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));return {backup:await workspaceStore.export(),revision:(await workspaceStore.personalMetadata()).revision};});
 expect(unchanged).toEqual({backup:fixture.backup,revision:fixture.revision});
 await page.evaluate(async()=>{
  const {workspaceStore}=await import(/* @vite-ignore */ String('/src/data/workspace.ts'));
  const data=await workspaceStore.load();data.goals[0].catalogBinding={state:'bound',snapshotId:'sha256:'+ '0'.repeat(64)};
  await workspaceStore.import(JSON.stringify({schemaVersion:2,scope:'craft',workspace:data,snapshots:[],missingSnapshotIds:[data.goals[0].catalogBinding.snapshotId]}));
 });
 await page.goto(url+'/#/craft');await page.reload();
 await expect(page.getByText(/first: snapshot-missing/)).toBeVisible();
 await expect(page.getByRole('button',{name:'Complete arrow',exact:true})).toBeDisabled();
 await expect(page.getByRole('button',{name:'Complete Arrow',exact:true})).toBeEnabled();
});
