import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';

test('personal modules persist real Pal edits and base assignment without network', async ({page,baseURL})=>{
 const external:string[]=[]; const errors:string[]=[];
 page.on('request',request=>{if(!request.url().startsWith(baseURL!))external.push(request.url());});
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/#/breeding');
 await page.getByLabel('Nickname').fill('Integration worker');
 await page.getByRole('combobox',{name:'Gender',exact:true}).selectOption('female');
 await page.getByRole('button',{name:'Save Pal',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Integration worker',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit Integration worker',exact:true}).click();
 await page.getByLabel('Nickname').fill('Edited worker');
 await page.getByLabel('Notes',{exact:true}).fill('Persisted field notes');
 await page.getByRole('button',{name:'Save Pal',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Edited worker',exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('Persisted field notes',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Bases',exact:true}).click();
 await page.getByLabel('Base name').fill('Integration base');
 await page.getByRole('checkbox',{name:/Edited worker/}).check();
 await page.getByRole('button',{name:'Save base',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Integration base',exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('1 / 15 workers · 0 / 0 simultaneous slots covered',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Today',exact:true}).click();
 await expect(page.getByText('1 active Pals · 0 archived · 0 saved breeding routes',{exact:true})).toBeVisible();
 await expect(page.getByText('No work slots configured; coverage has not been assessed.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Find a recipe',exact:true}).click();
 await page.getByLabel('Search recipes').fill('Arrow');
 await page.getByRole('button',{name:'Select Arrow',exact:true}).click();
 await page.getByRole('button',{name:'Pin craft goal',exact:true}).click();
 await expect(page.getByRole('heading',{name:/Arrow · 0 \//})).toBeVisible();
 await page.getByRole('link',{name:'Settings',exact:true}).click();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export Pal backup',exact:true}).click();
 const download=await downloadPromise; const backupPath=await download.path();
 expect(backupPath).toBeTruthy();
 await page.getByLabel('Preview Pal backup JSON (maximum 10 MiB)').setInputFiles(backupPath!);
 await expect(page.getByText('1 Pals, 1 bases, 0 routes',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Replace Pal data',exact:true})).toBeDisabled();
 await page.getByRole('checkbox',{name:'I have backed up my current data and confirm replacing all Pals, bases and routes.',exact:true}).check();
 await page.getByRole('button',{name:'Replace Pal data',exact:true}).click();
 await expect(page.getByText('Pal, base and route backup restored.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Today',exact:true}).click();
 await expect(page.getByText('No work slots configured; coverage has not been assessed.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Guild',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeDisabled();
 await page.reload();
 await expect(page.getByRole('heading',{name:'Guild workspace',exact:true})).toBeVisible();
 expect(external).toEqual([]); expect(errors).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('real guild UI signs up, signs in, creates and reads back shared task',async({page})=>{
 test.skip(process.env.GUILD_E2E!=='1','Opt in with GUILD_E2E=1 and running local guild services.');
 // Configuration is read only in Node. Only public endpoint URLs enter the page.
 const {authUrl,restUrl}=JSON.parse(readFileSync(process.env.GUILD_E2E_CONFIG || process.env.GUILD_BROWSER_CONFIG || new URL('../../scripts/guild/.local/config.json',import.meta.url),'utf8')) as {authUrl:string;restUrl:string};
 const suffix=randomUUID(); const email=`browser-${suffix}@example.test`; const password=`Browser-${randomUUID()}!`;
 const guildName=`Browser guild ${suffix}`; const taskTitle=`Browser task ${suffix}`;
 await page.goto('/#/guild');
 await page.getByLabel('Auth URL',{exact:true}).fill(authUrl);
 await page.getByLabel('REST URL',{exact:true}).fill(restUrl);
 await page.getByRole('button',{name:'Save endpoint URLs',exact:true}).click();
 await page.getByRole('checkbox',{name:/I trust both endpoints/}).check();
 await page.getByLabel('Email',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('checkbox',{name:'Create a new account',exact:true}).check();
 await page.getByRole('button',{name:'Sign up',exact:true}).click();
 await expect(page.getByText(`Signed in as ${email}`,{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await expect(page.getByText('Signed out. Session cleared from memory.',{exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:/I trust both endpoints/}).check();
 await page.getByRole('checkbox',{name:'Create a new account',exact:true}).uncheck();
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByText(`Signed in as ${email}`,{exact:true})).toBeVisible();
 await page.getByLabel('New guild name',{exact:true}).fill(guildName);
 await page.getByRole('button',{name:'Create guild',exact:true}).click();
 await expect(page.getByRole('heading',{name:guildName,exact:true})).toBeVisible();
 await expect(page.getByText('Your role: owner',{exact:true})).toBeVisible();
 await page.getByLabel('Shared task title',{exact:true}).fill(taskTitle);
 await page.getByRole('button',{name:'Create shared task',exact:true}).click();
 await expect(page.locator('.guild-tasks strong')).toHaveText(taskTitle);
 await page.getByRole('button',{name:'Claim task',exact:true}).click();
 await expect(page.getByRole('button',{name:'Claim task',exact:true})).toHaveCount(0);
 await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('done');
 await page.getByRole('button',{name:'Save task',exact:true}).click();
 await expect(page.locator('.guild-tasks')).toContainText('done · revision');
 await page.getByRole('button',{name:'Refresh from server',exact:true}).click();
 await expect(page.getByText('Loaded from server. No background sync.',{exact:true})).toBeVisible();
 await expect(page.locator('.guild-tasks strong')).toHaveText(taskTitle);
 await expect(page.locator('.guild-tasks')).toContainText('done · revision');
 await page.getByRole('link',{name:'Today',exact:true}).click();
 await expect(page.getByRole('region',{name:'Optional guild planning'})).toContainText('Session retained in memory');
 await page.getByRole('link',{name:'Guild',exact:true}).click();
 await expect(page.getByText(`Signed in as ${email}`,{exact:true})).toBeVisible();
 await expect(page.locator('.guild-tasks strong')).toHaveText(taskTitle);
 // Navigation retains the memory-only session; a document reload must not.
 await page.reload();
 await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeDisabled();
 await expect(page.locator('.guild-tasks')).toHaveCount(0);
});
