import { useState } from 'react';
import type { SharedStock, Task } from './client';
import { proposedTask, type RejectedProposal } from './conflicts';
export function ConflictComparison({proposal,tasks,stock,owner,user,disabled,onConfirm,onDiscard}:{proposal:RejectedProposal;tasks:Task[];stock:SharedStock[];owner:boolean;user:string;disabled:boolean;onConfirm:()=>void;onDiscard:()=>void}) {
 const [confirmed,setConfirmed]=useState(false);
 const current=proposal.kind==='task'?tasks.find(t=>proposal.input.p_action==='create' ? !!proposal.input.p_source_requirement && t.source_requirement_id===proposal.input.p_source_requirement && !['done','cancelled'].includes(t.status) : t.id===proposal.input.p_task):stock.find(s=>s.item_id===proposal.input.p_item);
 const next=proposal.kind==='task' ? current ? proposedTask(proposal.input,current as Task,user) : proposal.input : {item_id:proposal.input.p_item,quantity:proposal.input.p_quantity,revision:(current as SharedStock|undefined)?.revision??0};
 const task=proposal.kind==='task'?current as Task|undefined:undefined;
 const allowed=proposal.kind==='stock' || (!!task && proposal.input.p_action==='update' && (owner || task.assignee===user)) || (!!task && proposal.kind==='task' && proposal.input.p_action==='claim' && !task.assignee && !['done','cancelled'].includes(task.status));
 return <fieldset disabled={disabled}><legend>Review confirmed conflict</legend><p>The rejected request did not save. Compare the latest server snapshot with your proposal. Reapply uses this latest revision and a NEW idempotency key. Another change can conflict again. Proposed values show intended task fields; revision and timestamps remain the loaded comparison context until the server saves.</p><h4>Current server values</h4><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(current??'Not present',null,2)}</pre><h4>Proposed values</h4><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(next,null,2)}</pre>{proposal.kind==='task' && proposal.input.p_action==='claim' && <p>Proposed action: claim for your signed-in user.</p>}{proposal.kind==='task' && proposal.input.p_action==='create' && task && <button onClick={()=>{onDiscard();document.getElementById(`guild-task-${task.id}`)?.focus();}}>Review existing active task</button>}{!allowed && <p>This action cannot be reapplied with your current role or task state. Discard and review the task.</p>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed current and proposed values and reconfirm any source checksum and quantity changes</label><button disabled={!confirmed || !allowed} onClick={()=>{setConfirmed(false);onConfirm();}}>Confirm and reapply</button><button onClick={onDiscard}>Discard rejected proposal</button></fieldset>;
}
