import {useEffect,useState} from 'react';
import {liveQuery} from 'dexie';
import {catalog,speciesName,enumerateRoutes,parentGuidance,routeWarnings,analyzeBase,workTypes,type Pal,type Base,type BreedingRoute,type SavedRoute} from './domain';
import {palStore,type PalStore,type PalSnapshot} from './storage';
import './pals.css';
export interface WorkspaceProps {store?:PalStore; onTargetSpecies?:(speciesId:string)=>void}
export interface PalWorkspaceProps extends WorkspaceProps {initialTargetSpeciesId?:string}
function useWorkspace(store:PalStore){
 const [data,setData]=useState<PalSnapshot|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{
  let active=true;
  const fail=(e:unknown)=>{if(active)setError(`Storage unavailable: ${e instanceof Error?e.message:String(e)}`);};
  // liveQuery can wait for a closed database to reopen; direct initial read surfaces that failure.
  void store.snapshot().then(value=>{if(active)setData(value);}).catch(fail);
  const sub=liveQuery(()=>store.snapshot()).subscribe({next:value=>{if(active)setData(value);},error:fail});
  return()=>{active=false;sub.unsubscribe();};
 },[store,retry]);
 async function run(action:()=>Promise<unknown>){setError('');setBusy(true);try{await action();setData(await store.snapshot());return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}finally{setBusy(false);}}
 return {data,error,busy,run,retry:()=>{setError('');setRetry(n=>n+1);}};
}
function Notice(){return <aside className="pw-notice"><strong>Limited historical reference · compatibility unverified</strong><p>{catalog.species.length} species, {catalog.breedingPairs.length} explicit pairs. Unsupported pairs are not impossible. No perfect-passive guarantees or full-database optimality. Work levels are source snapshot values, not current-game verified throughput.</p><small>Source: <a href="https://github.com/tylercamp/palcalc/tree/d040d12ad362167e99937601b39714c4a145db94">Pal Calc v1.20.2</a> · MIT · Copyright 2024, Tyler Camp · {catalog.catalogId}</small></aside>;}
const newPal=():Pal=>({id:crypto.randomUUID(),speciesId:catalog.species[0].id,nickname:'',gender:'unknown',passives:[],notes:'',location:'',archived:false});
const labelPal=(p:Pal)=>p.nickname||speciesName(p.speciesId);
function RouteView({route,pals,saved,onSave,onRemove}:{route:BreedingRoute;pals:Pal[];saved?:SavedRoute;onSave:(r:SavedRoute)=>void;onRemove?:()=>void}){
 function parentLabel(ref:string){if(ref.startsWith('owned:')){const p=pals.find(p=>p.id===ref.slice(6));return p?`${labelPal(p)} (${p.gender}${p.archived?', archived — unavailable':''})`:`Missing owned individual ${ref.slice(6)}`;}const i=route.steps.findIndex(s=>`step:${s.id}`===ref);return `Offspring from step ${i+1} (gender unknown)`;}
 const warnings=routeWarnings(route,pals);
 return <article className="pw-card"><h4>{speciesName(route.targetId)} · {route.steps.length} step(s)</h4><p>{route.conditional?'Conditional: confirm compatible offspring/unknown parent gender.':warnings.length?'Saved route requires attention.':'Known first-step parent genders are compatible.'}</p>{warnings.map((warning,i)=><p role="status" key={i}>{warning}</p>)}<ol>{route.steps.map((step,i)=><li key={step.id}><p>{step.parents.map(parentLabel).join(' + ')} → <strong>{speciesName(step.childId)}</strong></p>{saved&&<label><input type="checkbox" checked={saved.completed.includes(step.id)} onChange={e=>onSave({...saved,completed:e.target.checked?[...saved.completed,step.id]:saved.completed.filter(id=>id!==step.id)})}/>Step {i+1} complete (manual)</label>}</li>)}</ol><small>Source version: {route.sourceVersion}. Parents are reusable; checking a step does not create a roster Pal.</small>{saved?<button type="button" onClick={onRemove}>Remove saved route</button>:<button type="button" onClick={()=>onSave({...route,completed:[]})}>Save route checklist</button>}</article>;
}
export function PalWorkspace({store=palStore,initialTargetSpeciesId}:PalWorkspaceProps){
 const state=useWorkspace(store);const [draft,setDraft]=useState<Pal>(newPal);const [target,setTarget]=useState(initialTargetSpeciesId??'Ronin');const [showArchived,setShowArchived]=useState(false);
 useEffect(()=>{if(initialTargetSpeciesId)setTarget(initialTargetSpeciesId);},[initialTargetSpeciesId]);
 const routes=enumerateRoutes(state.data?.pals??[],target);
 return <section className="pw-workspace" aria-label="Pal roster and breeding"><h2>Pal roster & breeding</h2><Notice/>{state.error&&<div role="alert">{state.error}<button onClick={state.retry}>Retry storage</button></div>}{!state.data&&!state.error&&<p role="status">Loading Pals…</p>}{state.data&&<>
 <div className="pw-columns"><section><h3>Your individuals</h3><label><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Show archived</label>{state.data.pals.length===0&&<p>No Pals yet. Add your first individual below.</p>}{state.data.pals.filter(p=>showArchived||!p.archived).map(p=><article className="pw-card" key={p.id}><h4>{labelPal(p)}</h4><p>{speciesName(p.speciesId)} · {p.gender} {p.archived?'· Archived':''}</p><p>{p.location} {p.passives.join(', ')}</p><p className="pw-notes">{p.notes}</p><small>Individual ID: {p.id}</small><div className="pw-actions"><button aria-label={`Edit ${labelPal(p)}`} onClick={()=>setDraft({...p})}>Edit</button><button disabled={state.busy} aria-label={`${p.archived?'Restore':'Archive'} ${labelPal(p)}`} onClick={()=>void state.run(()=>store.savePal({...p,archived:!p.archived}))}>{p.archived?'Restore':'Archive'}</button><button disabled={state.busy} aria-label={`Remove ${labelPal(p)}`} onClick={()=>{if(window.confirm(`Permanently remove ${labelPal(p)}? Base assignments will be released; saved routes keep the missing-parent link.`))void state.run(()=>store.removePal(p.id));}}>Remove</button></div></article>)}</section>
 <form className="pw-card" onSubmit={async e=>{e.preventDefault();if(await state.run(()=>store.savePal(draft)))setDraft(newPal());}}><h3>{state.data.pals.some(p=>p.id===draft.id)?'Edit individual':'Add individual'}</h3><label>Species<select value={draft.speciesId} onChange={e=>setDraft({...draft,speciesId:e.target.value})}>{catalog.species.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Nickname<input maxLength={100} value={draft.nickname} onChange={e=>setDraft({...draft,nickname:e.target.value})}/></label><label>Gender<select value={draft.gender} onChange={e=>setDraft({...draft,gender:e.target.value as Pal['gender']})}><option value="unknown">Unknown</option><option value="male">Male</option><option value="female">Female</option></select></label><label>Passives (comma separated; notes only)<input value={draft.passives.join(',')} onChange={e=>setDraft({...draft,passives:e.target.value.split(',')})}/></label><label>Location<input maxLength={200} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label>Notes<textarea maxLength={4000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="pw-actions"><button disabled={state.busy} type="submit">Save Pal</button><button type="button" onClick={()=>setDraft(newPal())}>New / cancel edit</button></div></form></div>
 <section><h3>Supported breeding routes</h3><label>Target species<select value={target} onChange={e=>setTarget(e.target.value)}>{catalog.species.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p>Bounded search: up to 4 breeding steps and 40 alternatives; explicit pairs only. Future offspring gender is unknown.</p>{!routes.length&&<p>No supported route from your active individuals within these bounds.</p>}<ul>{parentGuidance(state.data.pals,target).map(text=><li key={text}>{text}</li>)}</ul>{routes.map(r=><RouteView key={r.id} route={r} pals={state.data!.pals} onSave={r=>void state.run(()=>store.saveRoute(state.data!.routes.find(saved=>saved.id===r.id)??r))}/>)}</section><section><h3>Saved route checklists</h3>{!state.data.routes.length&&<p>No saved routes.</p>}{state.data.routes.map(r=><RouteView key={r.id} route={r} saved={r} pals={state.data!.pals} onSave={r=>void state.run(()=>store.saveRoute(r))} onRemove={()=>void state.run(()=>store.removeRoute(r.id))}/>)}</section></>}</section>;
}
const newBase=():Base=>({id:crypto.randomUUID(),name:'',capacity:15,workerIds:[],slots:[]});
export function BaseWorkspace({store=palStore,onTargetSpecies}:WorkspaceProps){
 const state=useWorkspace(store);const [draft,setDraft]=useState<Base>(newBase);
 return <section className="pw-workspace" aria-label="Base planning"><h2>Base planning</h2><Notice/>{state.error&&<div role="alert">{state.error}<button onClick={state.retry}>Retry storage</button></div>}{!state.data&&!state.error&&<p role="status">Loading bases…</p>}{state.data&&<><p>One individual per base; one simultaneous slot per worker. Priority 10 is highest. Suggestions are suitability-based scores, not throughput, and never move workers automatically.</p><div className="pw-columns"><section><h3>Your bases</h3>{!state.data.bases.length&&<p>No bases yet. Create a base below.</p>}{state.data.bases.map(base=>{const report=analyzeBase(base,state.data!.pals,state.data!.bases);return <article className="pw-card" key={base.id}><h4>{base.name}</h4><p>{base.workerIds.length} / {base.capacity} workers · {report.assignments.length} / {base.slots.length} simultaneous slots covered</p><ul>{report.assignments.map(a=><li key={a.slotId}>{labelPal(state.data!.pals.find(p=>p.id===a.palId)!)} → {base.slots.find(s=>s.id===a.slotId)?.work}</li>)}</ul>{report.shortage>0&&<p role="status">Worker shortage: {report.shortage} simultaneous slot(s) uncovered, including shared-worker conflicts.</p>}{report.unsuitable.length>0&&<p>Unsuitable for configured slots: {report.unsuitable.map(id=>labelPal(state.data!.pals.find(p=>p.id===id)!)).join(', ')}</p>}{report.idle.length>0&&<p>Unmatched workers: {report.idle.map(id=>labelPal(state.data!.pals.find(p=>p.id===id)!)).join(', ')}</p>}{report.gaps.map(slot=><div key={slot.id}><strong>Gap: {slot.work}, minimum {slot.minimum}, priority {slot.priority}</strong><ul>{report.replacements.filter(r=>r.slotId===slot.id).map(r=><li key={r.palId}>Consider {labelPal(state.data!.pals.find(p=>p.id===r.palId)!)} — score {r.score}: {r.reason}</li>)}</ul><p>Capture / breeding targets from this partial reference:</p><div className="pw-actions">{catalog.species.filter(s=>(s.workSuitability as Record<string,number>)[slot.work]>=slot.minimum).map(s=><button key={s.id} type="button" disabled={!onTargetSpecies} onClick={()=>onTargetSpecies?.(s.id)}>{s.name}</button>)}</div>{!onTargetSpecies&&<small>Choose these targets in the breeding workspace. Capture availability is not provided by this reference.</small>}</div>)}<div className="pw-actions"><button aria-label={`Edit ${base.name}`} onClick={()=>setDraft(structuredClone(base))}>Edit</button><button onClick={()=>{if(window.confirm(`Remove base ${base.name}?`))void state.run(()=>store.removeBase(base.id));}}>Remove base</button></div></article>;})}</section>
 <form className="pw-card" onSubmit={async e=>{e.preventDefault();if(await state.run(()=>store.saveBase(draft)))setDraft(newBase());}}><h3>{state.data.bases.some(b=>b.id===draft.id)?'Edit base':'Create base'}</h3><label>Base name<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Worker capacity<input type="number" min={1} max={100} required value={draft.capacity} onChange={e=>setDraft({...draft,capacity:Number(e.target.value)})}/></label><fieldset><legend>Assigned individuals</legend>{!state.data.pals.some(p=>!p.archived)&&<p>Add active individuals in the roster first.</p>}{state.data.pals.filter(p=>!p.archived).map(p=>{const other=state.data!.bases.find(b=>b.id!==draft.id&&b.workerIds.includes(p.id));return <label key={p.id}><input type="checkbox" disabled={!!other} checked={draft.workerIds.includes(p.id)} onChange={e=>setDraft({...draft,workerIds:e.target.checked?[...draft.workerIds,p.id]:draft.workerIds.filter(id=>id!==p.id)})}/>{labelPal(p)} · {speciesName(p.speciesId)} {other?`(assigned to ${other.name})`:''}</label>;})}</fieldset><h4>Simultaneous work slots</h4>{draft.slots.map((slot,i)=><fieldset key={slot.id}><legend>Slot {i+1}</legend><label>Work<select value={slot.work} onChange={e=>setDraft({...draft,slots:draft.slots.map(s=>s.id===slot.id?{...s,work:e.target.value}:s)})}>{workTypes.map(work=><option key={work}>{work}</option>)}</select></label><label>Minimum suitability<input type="number" required min={1} max={10} value={slot.minimum} onChange={e=>setDraft({...draft,slots:draft.slots.map(s=>s.id===slot.id?{...s,minimum:Number(e.target.value)}:s)})}/></label><label>Priority<input type="number" required min={1} max={10} value={slot.priority} onChange={e=>setDraft({...draft,slots:draft.slots.map(s=>s.id===slot.id?{...s,priority:Number(e.target.value)}:s)})}/></label><button type="button" onClick={()=>setDraft({...draft,slots:draft.slots.filter(s=>s.id!==slot.id)})}>Remove slot {i+1}</button></fieldset>)}<button type="button" onClick={()=>setDraft({...draft,slots:[...draft.slots,{id:crypto.randomUUID(),work:workTypes[0],minimum:1,priority:5}]})}>Add work slot</button><div className="pw-actions"><button disabled={state.busy} type="submit">Save base</button><button type="button" onClick={()=>setDraft(newBase())}>New / cancel edit</button></div></form></div></>}</section>;
}
